### ISSUE TITLE
Add the ETH domain

### ISSUE THREAD

**Issue by AboldUSER** [EthBuilders/Curriculum#11]
Direct the eth domain to the hosted website, such as through fleek.co

**Comment by skellet0r** [comment]
@AboldUSER moving over to a hosting provider is a great idea, and the fact that we use a static framework should make it even easier. We should definitely look into finding a good hosting provider, one which has a very high build minutes allotment.

For reference:
GitHub (our current hosting setup): free tier = 2,000 build minutes/month/user
Netlify: free tier = 300 build minutes/month
render.com: free tier = 100gb/month bandwith? (need more research on this, may reach out to support to clarify on build minutes)
Fleek.co: free tier =  250 build minutes/month

Currently our site takes about ~40ms to ~65ms to build, however there is major overhead depending on the CI/CD provider and that timing will usually increase to about 1 minute. So it's important our hosting platform allots us a considerable amount of build time, just to err on the side of caution.

Relevant article about what `bandwith` actually means to hosting providers: https://community.netlify.com/t/what-does-actually-count-in-bandwidth/28605/3.

I certainly did not know what was meant by bandwith so that was a good read.

**Comment by tesla809** [comment]
@AboldUSER Congrats on your first issue!!! WOOHOO!!!

@skellet0r thanks for detailed comment!

Related to the hosting, I think we can split it into two categories:
1. interesting to do
2. efficient

We can attempt to deploy to Fleek or Textile some IPFS based service as an experiment. It will allow us to write a good "how to do" lesson for members to try out on their own. Then I can reach out to whichever we pick and persuade them to donate more resources as a win-win. We get resources and they get an audience of future devs who may use their service in the future and good demo. We are the demographic they are trying to target.

@AboldUSER could you start the research on this?

For efficiency and pragmatism's sake, we can continue to build out the MVP on a platform that is easy to push to, cheap (or free), scalable. 

@skellet0r  is it possible to push to Github and another location like Fleek at the same time? Or say, push to IPFS as backup weekly/monthly and our GitHub more often as our main location? 

Too complex? Ideally, I want to reduce complexity in things early on.

**Comment by skellet0r** [comment]
@tesla809 yep, we can definitely deploy to multiple places at once (i.e. github and fleek). Since the github deployment is already setup not too much to worry about there. In terms of another platform, I'll verify to see if they have timed automated deploys. To work as you said kind of like an archive/backup for the time being.

**Comment by AboldUSER** [comment]
@tesla809 I'll get on the research piece to look at a few IPFS hosting providers and put together a 'how to' guide for it.

**Comment by Islandersfan2016** [comment]
@tesla809 Would using ENS as a service be helpful?
